spring.application.name: processApplication
server.port: 8087
camunda:
  bpm:
    datasource:
      jdbcUrl: jdbc:h2:mem:camundaDB;MODE=Oracle;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      driverClassName: org.h2.Driver
      platform: h2
      username: sa
      password: sa
      schema-update: true
    admin-user:
      id: admin
      password: admin
      firstName: Admin
    application:
      delete-upon-undeploy: false
      scan-for-process-definitions: true
      deploy-changed-only: true
      resume-previous-versions: true
      resume-previous-by: a value
    default-serialization-format: application/json
    filter:
      create: All tasks
    job-execution:
      enabled: true
    metrics:
      enabled: false
db-reporter-activate: false